### PR TITLE
rebuild

### PR DESCRIPTION
**Pull request by beckermr**
…nda-forge-pinning 2019.01.21

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

Closes #4

### CODE REVIEW

**Comment by adrn** [comment]
* Gala no longer supports 2.7
* The 3.7 failures are because of Cython issues (should be resolved by the release of gala v1.0 soon!)

Thanks for the help!

**Comment by beckermr** [comment]
OK @adrn. I have gone ahead and adjusted the meta.yaml for those comments. When v1.0 comes out, simple undo the python version restriction and rerender to enable python 3.7

**Comment by beckermr** [comment]
I suggest you merge this PR as is so that this package is at least on the new conda channel for gcc7 in some form.

**Comment by adrn** [comment]
Thanks @beckermr -- I really appreciate it!

**Pull request merged**
